app:
  version: "@project.version@"
vep:
  port: 8080
  forks: 4
  host: 8080
  username:
  password:
  hgvs-max-threads: 75
  polyphen-sift-filename: "canis_lupus_familiaris_core_104_31.sql"
  alpha-missense-filename: