app:
  version: "@project.version@"
vep:
  port: 8080
  forks: 4
  host: 8008
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  hgvs-max-threads: 75
  polyphen-sift-filename: "canis_lupus_familiaris_core_104_31.sql"
  alpha-missense-filename:
