app:
  version: "@project.version@"
vep:
  port: ${MYSQL_PORT}
  forks: 4
  host: ${MYSQL_HOST}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  hgvs-max-threads: 75
  polyphen-sift-filename:
  alpha-missense-filename: