app:
  version: "@project.version@"
vep:
  port: 8080
  forks: 4
  host: 8080
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  hgvs-max-threads: 75
  polyphen-sift-filename:
  alpha-missense-filename: